### ISSUE TITLE
Doesn't work on Fire 8 tablet with multiple devices

### ISSUE THREAD

**Issue by brianlmerritt** [thorpelawrence/alexa-spotify-connect#53]
I have a Sony RX amp with Spotify Connect enabled, and via the Spotify app it connects fine.  However, having enabled the skill (and clicking on the link etc) then Alexa ask connect control to list devices works fine but transfer to device 2 does not affect the tablet - it keeps playing locally on the tablet.

**Comment by thorpelawrence** [comment]
Hey there,

Does the amp show in the Spotify desktop/mobile/web interface under the connect devices list? If you choose the device does it transfer as it should?

I've heard some similar issues with e.g. Sonos systems, and I suspect it's something to do with the Spotify API not allowing transfer to those devices because they are treated differently somehow, although I haven't had time to research this unfortunately

**Comment by brianlmerritt** [comment]
Hi - the Sony appears on Windows, Mac, iOS, & Android apps, and the transfer works fine.  Using the connect control skill it can find the device,  just not transfer to it.

**Comment by brianlmerritt** [comment]
If I go to my Spotify account, there doesn't appear to be any app related to connect control linking to the account.  When I disable this skill and re-enable it I get the link to Spotify (and I'm logged into Spotify on the browser separately) but it doesn't seem to be linking the skill in Spotify itself...

**Comment by thorpelawrence** [comment]
Am I correct in understanding that even after trying twice, it isn't showing as an authorised app in your Spotify account?

**Comment by brianlmerritt** [comment]
Closing as I have stopped using Alexa
