### ISSUE TITLE
I have linked my Spotify account but the skill doesn't recognize it

### ISSUE THREAD

**Issue by Guillerm097** [thorpelawrence/alexa-spotify-connect#57]
Hi, after I have deployed the webapp, I try to use it on my Echo device and it keeps telling me that I have not linked my Spotify account but I have. What could be the problem? I tried to unlink and link my Spotify account twice but nothing seems to change. In my Spotify account I can see Amazon Alexa as an approved application. I can use Spotify without using this skill so I guess it is well-connected?

Btw, I have another doubt: when I deploy this app to heroku using github, it gives me build error because I have two lock files (yarn.lock and package-lock.json and yarn.lock... As far as I understand yarn.lock is just used to run the test so if I delete it, should I have any problem?

Thank you in advance!!

**Comment by thorpelawrence** [comment]
Hi there,

It might be an issue with it trying to connect to my version instead of yours if you are hosting it yourself, I would double check that whatever URLs entered in the Spotify dev account are correctly pointing to yours if you are self hosting

I build this package with `yarn` instead of `npm` so it might be that running `npm install` creates the additional file which heroku does not like, so you might be able to delete the `yarn.lock` file if you are using npm instead of yarn, although I have not tested it

**Comment by Guillerm097** [comment]
Hi, I finally ended up building the package with yarn too. I also checked the Spotify URLs and I noticed they weren't pointing to my skill's redirect URLs, big fail, but it still doesn't work. I have also rechecked the 6-steps to deploy the skill and I don't see anything wrong...
About the version issue, what could I do to fix it?
Thank you, I appreciate it.
